config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :events
  resources :vacunas
  resources :companeros

  root to: 'companeros#index'

  
resources :companeros do
  resources :vacunas
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/companero.rb
class Companero < ApplicationRecord
    has_many :vacunas
    
    mount_uploader :foto, FotoUploader
    validates :contacto, length: {maximum: 10}
    validates :edad,  numericality: {only_integer: true, message: "Sólo números!!"}
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
    validates :direccion, :animal, :descripcion, :color, :peso, :tamano, :raza, :dueno, presence: true

def self.search(search)
  where("nombre LIKE ? OR edad LIKE ? OR raza LIKE ? OR dueno LIKE ? OR descripcion LIKE ?
  OR color LIKE ? OR peso LIKE ? OR tamano LIKE ? OR animal LIKE ?",
  "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%",
  "%#{search}%", "%#{search}%" , "%#{search}%") 
end

end

app/controllers/companeros_controller.rb
class CompanerosController < ApplicationController
  before_action :set_companero, only: [:show, :edit, :update, :destroy]



  # GET /companeros
  # GET /companeros.json
  def index
    @companeros = Companero.order(:dueno)
    if params[:search]
      @companeros = Companero.search(params[:search]).order(:dueno)
    else
      @companeros = Companero.all.order(:dueno)
    end
  end

  class CompaneroPdf < Prawn::Document
    def initialize(companero)
        super(top_margin: 70, left_margin: 50, right_margin: 50)
        @companero = companero
        companero_id
        
    end

    def companero_id
      pdf = Prawn::Document.new
      text "Mascota #{@companero.nombre}", size:30, style: :bold
      text ("")
      text "____________________________________________________________________________", size: 12
      text "\n"
      text "Edad: ", size: 14, style: :bold
      text "#{@companero.edad}", size: 12
      text "\n"
      text "Raza: ", size: 14, style: :bold
      text "#{@companero.raza}", size: 12
      text "\n"
      text "Descripción: ", size: 14, style: :bold
      text "#{@companero.descripcion}", size: 12
      text "\n"
      text "Color: ", size: 14, style: :bold
      text "#{@companero.color}", size: 12
      text "\n"
      text "Peso: ", size: 14, style: :bold
      text "#{@companero.peso}", size: 12
      text "\n"
      text "Tamaño: ", size: 14, style: :bold
      text "#{@companero.tamano}", size: 12
      text "\n"
      text "Animal: ", size: 14, style: :bold
      text "#{@companero.animal}", size: 12
      text "\n"
      text "Dueño: ", size: 14, style: :bold
      text "#{@companero.dueno}", size: 12
      text "\n"
      text "Dirrección: ", size: 14, style: :bold
      text "#{@companero.direccion}", size: 12
      text "\n"
      text "Telefono: ", size: 14, style: :bold
      text "#{@companero.contacto}", size: 12
      end    
end
  # GET /companeros/1
  # GET /companeros/1.json
  def show
    @companero = Companero.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = CompaneroPdf.new(@companero)
        send_data pdf.render, filename: "companero_#{@companero.nombre}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
        end
      end
  end

  # GET /companeros/new
  def new
    @companero = Companero.new
  end

  # GET /companeros/1/edit
  def edit
  end

  # POST /companeros
  # POST /companeros.json
  def create
    @companero = Companero.new(companero_params)

    respond_to do |format|
      if @companero.save
        format.html { redirect_to @companero, notice: 'La mascota fue creada con exito.' }
        format.json { render :show, status: :created, location: @companero }
      else
        format.html { render :new }
        format.json { render json: @companero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companeros/1
  # PATCH/PUT /companeros/1.json
  def update
    respond_to do |format|
      if @companero.update(companero_params)
        format.html { redirect_to @companero, notice: 'La mascota fue editada con exito.' }
        format.json { render :show, status: :ok, location: @companero }
      else
        format.html { render :edit }
        format.json { render json: @companero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companeros/1
  # DELETE /companeros/1.json
  def destroy
    @companero.destroy
    respond_to do |format|
      format.html { redirect_to companeros_url, notice: 'La mascota fue eliminada con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_companero
      @companero = Companero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def companero_params
      params.require(:companero).permit(:fecha, :nombre, :edad, :raza, :dueno, :descripcion, :color, :peso, :tamano, :foto, :animal, :direccion, :contacto, :email)
    end
end

app/helpers/companeros_helper.rb
module CompanerosHelper
end

app/views/companeros/_form.html.erb
<%= form_for(companero) do |f| %>
  <% if companero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(companero.errors.count, "error") %> prohibited this companero from being saved:</h2>

      <ul>
      <% companero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="small-5 large-4 columns">
   <div class="field">
    <%= f.label :Nombre %>
    <%= f.text_field :nombre %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= f.label :Edad %>
    <%= f.number_field :edad %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= f.label :Animal %>
    <%= f.select :animal, ['Gato', 'Perro', 'Tortuga', 'Pajaro', 'Serpiente', 'Hámster', 'Pez']%>
  </div>
  </div>
</div>

<div class="row">
  <div class="small-5 large-8 columns">
   <div class="field">
    <%= f.label :Descripción %>
    <%= f.text_field :descripcion %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
<div class="field">
    <%= f.label :Color %>
    <%= f.text_field :color%>
  </div>
  </div>
</div>

<div class="row">
  <div class="small-5 large-4 columns">
     <div class="field">
    <%= f.label :Peso %>
    <%= f.text_field :peso %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= f.label :Tamaño %>
    <%= f.select :tamano, ['Miniatura', 'Chico', 'Mediano', 'Grande', 'Gigante']%>
  </div>
  </div>
  <div class="small-5 large-4 columns">
<div class="field">
    <%= f.label :Foto %>
    <%= f.file_field :foto %>
  </div>
  </div>
</div> 

<div class="row">
  <div class="small-5 large-8 columns">
    <div class="field">
    <%= f.label :Raza %>
    <%= f.text_field :raza%>
  </div>
  </div>
  <div class="small-5 large-4 columns">

  </div>
</div>


<h1>Datos del dueño</h1>
<div class="row">
  <div class="small-5 large-4 columns">
   <div class="field">
    <%= f.label :Telefono %>
    <%= f.number_field :contacto %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= f.label :Direccion %>
    <%= f.text_field :direccion %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= f.label :Dueño %>
    <%= f.text_field :dueno %>
  </div>
  </div>
</div>
 
<div class="row">
  <div class="small-5 large-8 columns">
   <div class="field">
    <%= f.label :Email %>
    <%= f.text_field :email %>
  </div>
  </div>
</div>

  
<div class="actions">
  <%= f.submit ( f.object.new_record? ? "Crear" : "Actualizar"), class: "button secondary" %>
  </div>
<% end %>

app/views/companeros/companeroBus.html.erb
  <% @companerosBus = Companero.where(@palabraB) %>
  
<table WIDTH="99%">
  <thead>
    <tr>
    <th colspan="2">Foto</th>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Raza</th>
      <th>Dueño</th>
      <th>Descripción</th>
      <th>Color</th>
      <th>Peso</th>
      <th>Tamaño</th>
      <th>Animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  </table>

app/views/companeros/edit.html.erb
<center>
<h1>Editando mascota</h1>

<%= render 'form', companero: @companero %>

<%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, @companero %> |
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, companeros_path %>|
<%= link_to '<button type="button" class="button warning basci">Inicio</button>'.html_safe, companeros_path %>

</center>

app/views/companeros/index.html.erb
<style>
img{
  max-width:  300%;
}
td{
  width: 40px;
}

table{
  vertical-align: center;
}
</style>
<center>
<p id="notice"><%= notice %></p>

<h1>Mascotas</h1>

<% if !@companeros.blank? %>

<table WIDTH="99%">
  <thead>
    <tr>
    <th colspan="2">Foto</th>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Raza</th>
      <th>Dueño</th>
      <th>Descripción</th>
      <th>Color</th>
      <th>Peso</th>
      <th>Tamaño</th>
      <th>Animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companeros.each do |companero| %>
      <tr>
      <td><%= image_tag(companero.foto_url)  %></td>
      <td></td>
        <td><%= companero.nombre %></td>
        <td><%= companero.edad %></td>
        <td><%= companero.raza %></td>
        <td><%= companero.dueno %></td>
        <td><%= companero.descripcion %></td>
        <td><%= companero.color %></td>
        <td><%= companero.peso %></td>
        <td><%= companero.tamano %></td>
        <td><%= companero.animal %></td>
        <td><%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, companero %></td>
        <% if current_user.role == "Doctor" %>
        <td><%= link_to '<button type="button" class="button success small">Editar</button>'.html_safe, edit_companero_path(companero) %></td>
        <td><%= link_to '<button type="button" class="button alert small">¡Eliminar!</button>'.html_safe, companero, method: :delete, data: { confirm: '¿Estas seguro?' } %>
        <% end %>
                </tr>
    <% end %>
  </tbody>
</table>

<br>

<% else %>
<div data-alert class="alert-box alert round large-5 small-7">
    No se encontró nada con <b>" <%= params[:search] %> "</b>
    <a href="#" class="close">&times;</a>
</div>

  <%= link_to '<button type="button" class="button">Inicio</button>'.html_safe, companeros_path %>
<% end %>

<%= link_to '<button type="button" class="button warning basci">Nueva Mascota</button>'.html_safe, new_companero_path %>
</center>

app/views/companeros/new.html.erb
<center>
<h1>Nueva Mascota</h1>

<%= render 'form', companero: @companero %>

<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, companeros_path %>
</center>

app/views/companeros/show.html.erb
<style>
img{
  max-width:  100%;
}
.imagen{
  width: 400px;
}
</style>

<%= link_to '<button type="button" class="button tiny success" id="open-hide">Generar PDF</button>'.html_safe, companero_path(@companero, format: "pdf") %>  

<div class="row">
  <div class="large-8 columns imagen">
  <%= image_tag(@companero.foto_url)%>
  </div>
<div class="large-4 columns">
<p>
  <strong>Nombre:</strong>
  <%= @companero.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @companero.edad %>
</p>

<p>
  <strong>Raza:</strong>
  <%= @companero.raza %>
</p>



<p>
  <strong>Descripción:</strong>
  <%= @companero.descripcion %>
</p>

<p>
  <strong>Color:</strong>
  <%= @companero.color %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @companero.peso %>
</p>

<p>
  <strong>Tamaño:</strong>
  <%= @companero.tamano %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @companero.animal %>
</p>

<p>
  <strong>Dueño:</strong>
  <%= @companero.dueno %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @companero.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @companero.contacto %>
</p>


</div>
</div>
<center>

<% if current_user.role == "Doctor" %>
<%= link_to '<button type="button" class="button success basic">Editar</button>'.html_safe, edit_companero_path(@companero) %> |
<% end %>
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, companeros_path %>


<div class="row">
<% if current_user.role == "Doctor" %>
  <div class="large-2 columns">
  <% else %>
  <div class="large-12 colums">
  <% end %> 
  <h2>Vacunas</h2>
<% @companero.vacunas.each do |vacuna| %>
   <p>
    <strong>Nombre:</strong>
    <%= vacuna.nombre %>
  </p>
  <p>
    <strong>Aplicación:</strong>
    <%= vacuna.aplicacion %>
  </p>
   <p>
    <strong>Doctor:</strong>
    <%= vacuna.doctor %>
  </p>
   <p>
    <strong>Tipo:</strong>
    <%= vacuna.tipo %>
  </p>
  <p>
    <strong>Fecha:</strong>
    <%= vacuna.fecha %>
  </p>
 <% end %>
  </div>

  <% if current_user.role == "Doctor" %>
<div class="large-6 columns">
<h2>Añadir vacuna</h2>
<%= form_for([@companero, @companero.vacunas.build]) do |f| %>
  <p>
    <%= f.label :nombre_del_medicamento %><br>
    <%= f.text_field :nombre %>
  </p>
  <p>
    <%= f.label :aplicación %><br>
    <%= f.select :aplicacion, ['Oral', 'Intradérmica', 'Subcutánea', 'Intramuscular'] %>
  </p>
   <p>
    <%= f.label :doctor %><br>
    <%= f.text_area :doctor %>
  </p>
   <p>
    <%= f.label :tipo %><br>
    <%= f.select :tipo, ['Refuerzo', 'Primera vez', 'Segunda vez', 'Tercera vez', 'Periodica'] %>
  </p>
  <p>
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
<% end %>
</div> </div>
</center>